USE [master]
GO

/****** Object:  Database [GameShop]    Script Date: 25/09/2016 4:57:15 PM ******/
CREATE DATABASE [GameShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GameShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\GameShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GameShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\GameShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GameShop] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GameShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GameShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GameShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GameShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GameShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GameShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [GameShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GameShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GameShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GameShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GameShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GameShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GameShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GameShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GameShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GameShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GameShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GameShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GameShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GameShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GameShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GameShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GameShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GameShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GameShop] SET  MULTI_USER 
GO

ALTER DATABASE [GameShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GameShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GameShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GameShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GameShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GameShop] SET QUERY_STORE = OFF
GO

USE [GameShop]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GameShop] SET  READ_WRITE 
GO


